version: '3'

services: 

  laravel: 
    image: hospedaapp/laravel:prod
    container_name: laravel
    # Este container irá fazer parte da rede laranet
    networks:
      - laranet

  nginx:
    image: hospedaapp/nginx:prod
    container_name: nginx
    # Este container irá fazer parte da rede laranet
    networks:
      - laranet
    ports:
      - "8080:80"

# Criando rede com nome de laranet cuja o drive será bridge
networks:
  laranet:
    driver: bridge